WebApplication1/Models/ErrorViewModel.cs
namespace WebApplication1.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebApplication1/Models/Usuario.cs
using Microsoft.Extensions.Hosting;

namespace WebApplication1.Models
{
    public class Usuario
    {
        public string Nombre { get; set; }
        public string Correo { get; set; }
        public string Clave { get; set; }

        public string[] Roles { get; set; }
    }

    public class UsuarioDto
    {
        public string UserName { get; set; }
        public string Password { get; set; }
    }

    public class TokensDto
    {
        public string AccesTokenActual { get; set; }
        public string AccessTokenLast { get; set; }
        public string Mensaje { get; set; }
        public bool IsSuccess { get; set; }

    }

    public class User
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
    }

    public class Libro
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Body { get; set; }
    }
}

WebApplication1/Controllers/AccesoController.cs
using Microsoft.AspNetCore.Mvc;

using WebApplication1.Models;
using WebApplication1.Data;

//1.- REFERENCES AUTHENTICATION COOKIE
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using System.Security.Claims;
using Newtonsoft.Json;
using System.Text;
using System;
using System.IdentityModel.Tokens.Jwt;

namespace WebApplication1.Controllers
{
    public class AccesoController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        //USAR REFERENCIAS Models y Data
        [HttpPost]
        public async Task<IActionResult> Index(Usuario _usuario)
        {
            //DA_Usuario _da_usuario = new DA_Usuario();

            //var usuario = _da_usuario.ValidarUsuario(_usuario.Correo,_usuario.Clave);

            var cliente = new HttpClient();
            cliente.BaseAddress = new Uri("http://200.7.103.154:99");
            cliente.DefaultRequestHeaders.Add("Apikey", "TKHYOADJQDUHSSPDTODUGVFWXTWPJOZF");
            cliente.DefaultRequestHeaders.Add("CodigoAplicacion", "f55dae5a-b9b9-45c6-aa9c-f417f5fecd8b");
            var content = new StringContent(JsonConvert.SerializeObject(new Models.UsuarioDto { UserName = _usuario.Correo, Password = _usuario.Clave }), Encoding.UTF8, "application/json");

            var response = await cliente.PostAsync("/api/loginazure", content);

            if (response.IsSuccessStatusCode)
            {
                var jsonResponse = await response.Content.ReadAsStringAsync();

                var resultado = JsonConvert.DeserializeObject<TokensDto>(jsonResponse);
                var claimsTokenAzure = await GetTokenInfo(resultado.AccesTokenActual);

                string permisos = claimsTokenAzure["role"];
                string[] permiso = permisos.Split(' ');

                //2.- CONFIGURACION DE LA AUTENTICACION
                #region AUTENTICACTION
                var claims = new List<Claim>
                {
                    new Claim(ClaimTypes.Name, claimsTokenAzure["unique_name"]),
                    new Claim("Correo",claimsTokenAzure["email"]),
                };
                foreach (string rol in permiso) {
                    claims.Add(new Claim(ClaimTypes.Role, rol));
                }
                var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);

                await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(claimsIdentity));
                #endregion


                return RedirectToAction("Index", "Home");
            }
            else {
                return View();
            }
            
        }

        public async Task<IActionResult> Salir()
        {
            //3.- CONFIGURACION DE LA AUTENTICACION
            #region AUTENTICACTION
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            #endregion

            return RedirectToAction("Index");

        }

        private async Task<Dictionary<string, string>> GetTokenInfo(string token)
        {
            var TokenInfo = new Dictionary<string, string>();

            var handler = new JwtSecurityTokenHandler();
            var jwtSecurityToken = handler.ReadJwtToken(token);
            var claims = jwtSecurityToken.Claims.ToList();

            foreach (var claim in claims)
            {
                TokenInfo.Add(claim.Type, claim.Value);
            }

            return TokenInfo;
        }

    }
}

WebApplication1/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using WebApplication1.Models;
using Microsoft.AspNetCore.Authorization;
using Newtonsoft.Json.Linq;
using System.Text.Json;
using Microsoft.DotNet.MSIdentity.Shared;
using Newtonsoft.Json;

namespace WebApplication1.Controllers
{
    //[Authorize]
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        [Authorize(Roles = "Admin,Supervisor,Operador,Ninguno")]
        public IActionResult Index()
        {
            return View();
        }

        [Authorize(Roles = "Admin,Supervisor,Operador")]
        public async Task<IActionResult> Ventas()
        {
            List<Libro> libros = new List<Libro>();
            string baseUrl = "http://200.7.103.154:99/api/posts";
            try
            {
                using (HttpClient client = new HttpClient())
                {
                    using (HttpResponseMessage res = await client.GetAsync(baseUrl))
                    {
                        using (HttpContent content = res.Content)
                        {
                            var data = await content.ReadAsStringAsync();
                            if (content != null)
                            {
                                libros = JsonConvert.DeserializeObject<List<Libro>>(data);
                            }
                            else
                            {
                                Console.WriteLine("NO Data----------");
                            }
                        }
                    }
                }
            }
            catch (Exception exception)
            {
                Console.WriteLine("Exception Hit------------");
                Console.WriteLine(exception);
            }
            return View(libros);
        }

        [Authorize(Roles = "Admin,Supervisor")]
        public IActionResult Compras()
        {
            return View();
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Clientes()
        {
            List<User> users = new List<User>();
            string baseUrl = "http://200.7.103.154:99/api/users";
            try
            {
                using (HttpClient client = new HttpClient())
                {
                    using (HttpResponseMessage res = await client.GetAsync(baseUrl))
                    {
                        using (HttpContent content = res.Content)
                        {
                            var data = await content.ReadAsStringAsync();
                            if (content != null)
                            {
                                users = JsonConvert.DeserializeObject<List<User>>(data);
                            }
                            else
                            {
                                Console.WriteLine("NO Data----------");
                            }
                        }
                    }
                }
            }
            catch (Exception exception)
            {
                Console.WriteLine("Exception Hit------------");
                Console.WriteLine(exception);
            }
            return View(users);
        }

        [AllowAnonymous]
        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebApplication1/Views/Acceso/Index.cshtml
@model Usuario
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
</head>
<body>

    @*------ GOOGLEAR ====> form bootstrap 5 ----------------*@

    <div class="row mt-5">
        <div class="col-sm-4 offset-sm-4">

         <form asp-controller="Acceso" asp-action="Index" method="post">
              <div class="mb-3">
                <label for="exampleInputEmail1" class="form-label">Email address</label>
                <input type="email" class="form-control" asp-for="Correo">
                @*<div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>*@
              </div>
              <div class="mb-3">
                <label for="exampleInputPassword1" class="form-label">Password</label>
                <input type="password" class="form-control" asp-for="Clave">
              </div>
             @* <div class="mb-3 form-check">
                <input type="checkbox" class="form-check-input" id="exampleCheck1">
                <label class="form-check-label" for="exampleCheck1">Check me out</label>
              </div>*@
              <button type="submit" class="btn btn-primary">Submit</button>
        </form>


        </div>
    </div>

  

</body>
   <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
</html>

WebApplication1/Views/Home/Clientes.cshtml
@using Microsoft.AspNetCore.Identity
@model List<User>
@{
    ViewData["Title"] = "Clientes";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@*<div class="text-center">
     <div class="alert alert-success">
        <h class="display-4">Soy la pagina CLIENTES</h>
    </div>
</div>*@

<div>
    <h1 class="display-4">Bienvenido</h1>
</div>

<div class="card">
    <div class="card-header">
        Lista Users
    </div>
    <div class="card-body">
        
        @*<a asp-action="Pais" asp-controller="Pais" asp-route-idPais="0" class="btn btn-success btn-sm">Nuevo Pais</a>*@
        <button type="button" class="btn btn-success btn-sm" onclick="ShowModal()" data-target="#exampleModal">Nuevo cliente</button>
        <hr />

        <table class="table">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Nombre</th>
                    <th>NombreUsuario</th>
                    <th>Email</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.Id</td>
                        <td>@item.Name</td>
                        <td>@item.UserName</td>
                        <td>@item.Email</td>
                        <td>
                            <button type="button" class="btn btn-info btn-sm" onclick="ShowModal()" data-target="#exampleModal">Editar</button>
                            <button type="button" class="btn btn-danger btn-sm" onclick="ShowModal()" data-target="#exampleModal">Eliminar</button>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Modal</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            @if (User.IsInRole("Admin"))
            {
                <div class="modal-body">
                    <p>Permiso concedido</p>
                </div>
            }
            else
            {
                <div class="modal-body">
                    <p>Permiso denegado</p>
                </div>
            }
            
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" onclick="HideModal()">Close</button>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    function ShowModal() {

        $("#exampleModal").modal('show');
    }

    function HideModal() {

        $("#exampleModal").modal('hide');
    }
</script>

WebApplication1/Views/Home/Compras.cshtml
@{
    ViewData["Title"] = "Compras";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="text-center">
    <div class="alert alert-success">
        <h2 class="display-4">Soy la pagina COMPRAS</h2>
    </div>
    
</div>

WebApplication1/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Bienvenido</h1>
    <p>Aplicacion cliente demo </p>
</div>

WebApplication1/Views/Home/Ventas.cshtml
@using Microsoft.AspNetCore.Identity
@model List<Libro>
@{
    ViewData["Title"] = "Ventas";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div>
    <h1 class="display-4">Bienvenido</h1>
</div>

<div class="card">
    <div class="card-header">
        Lista Libro
    </div>
    <div class="card-body">
        @*<a asp-action="Pais" asp-controller="Pais" asp-route-idPais="0" class="btn btn-success btn-sm">Nuevo Pais</a>*@
        <button type="button" class="btn btn-success btn-sm" onclick="ShowModal()" data-target="#exampleModal">Nuevo libro</button>
        <hr />

        <table class="table">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Titulo</th>
                    <th>Body</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.Id</td>
                        <td>@item.Title</td>
                        <td>@item.Body</td>
                        <td>
                            <button type="button" class="btn btn-info btn-sm" onclick="ShowModal()" data-target="#exampleModal">Editar</button>
                            <button type="button" class="btn btn-danger btn-sm" onclick="ShowModal()" data-target="#exampleModal">Eliminar</button>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Modal</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            @if (User.IsInRole("Admin"))
            {
                    <div class="modal-body">
                        <p>Permiso concedido</p>
                    </div>
            }
            else
            {
                    <div class="modal-body">
                        <p>Permiso denegado</p>
                    </div>
            }

            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" onclick="HideModal()">Close</button>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    function ShowModal() {

        $("#exampleModal").modal('show');
    }

    function HideModal() {

        $("#exampleModal").modal('hide');
    }
</script>

WebApplication1/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ClienteA</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApplication1.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Cliente A</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        
                       @* <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Ventas">Ventas</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Compras">Compras</a>
                        </li>

                        <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Clientes">Clientes</a>
                        </li>*@
                        
                        @if (User.IsInRole("Admin") || User.IsInRole("Supervisor") || User.IsInRole("Operador"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Ventas">Ventas</a>
                            </li>
                        }

                        @if (User.IsInRole("Admin") || User.IsInRole("Supervisor"))
                        {
                             <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Compras">Compras</a>
                             </li>
                        }

                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                 <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Clientes">Clientes</a>
                            </li>
                        }

                      @*  <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                       *@
                    </ul>
                    @*<partial name="_LoginPartial" />*@
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="" title="Manage">Hola @User.Identity?.Name!</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Acceso" asp-action="Salir">Salir</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Cliente A - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>